  METHOD generate_tax_codes.
    DATA: lt_codes TYPE TABLE OF zetr_t_taxcd,
          lt_texts TYPE TABLE OF zetr_t_taxcx.

    lt_codes = VALUE #( ( taxty = '0003' taxct = 'DGR' )
                        ( taxty = '0011' taxct = 'DGR' )
                        ( taxty = '0015' taxct = 'KDV' )
                        ( taxty = '0021' taxct = 'DGR' )
                        ( taxty = '0061' taxct = 'DGR' )
                        ( taxty = '0071' taxct = 'OTV' )
                        ( taxty = '0073' taxct = 'OTV' )
                        ( taxty = '0074' taxct = 'OTV' )
                        ( taxty = '0075' taxct = 'OTV' )
                        ( taxty = '0076' taxct = 'OTV' )
                        ( taxty = '0077' taxct = 'OTV' )
                        ( taxty = '1047' taxct = 'DGR' )
                        ( taxty = '1048' taxct = 'DGR' )
                        ( taxty = '4071' taxct = 'DGR' )
                        ( taxty = '4080' taxct = 'DGR' )
                        ( taxty = '4081' taxct = 'DGR' )
                        ( taxty = '4171' taxct = 'DGR' )
                        ( taxty = '601'  taxct = 'TEV' )
                        ( taxty = '602'  taxct = 'TEV' )
                        ( taxty = '603'  taxct = 'TEV' )
                        ( taxty = '604'  taxct = 'TEV' )
                        ( taxty = '605'  taxct = 'TEV' )
                        ( taxty = '606'  taxct = 'TEV' )
                        ( taxty = '607'  taxct = 'TEV' )
                        ( taxty = '608'  taxct = 'TEV' )
                        ( taxty = '609'  taxct = 'TEV' )
                        ( taxty = '610'  taxct = 'TEV' )
                        ( taxty = '611'  taxct = 'TEV' )
                        ( taxty = '612'  taxct = 'TEV' )
                        ( taxty = '613'  taxct = 'TEV' )
                        ( taxty = '614'  taxct = 'TEV' )
                        ( taxty = '615'  taxct = 'TEV' )
                        ( taxty = '616'  taxct = 'TEV' )
                        ( taxty = '617'  taxct = 'TEV' )
                        ( taxty = '618'  taxct = 'TEV' )
                        ( taxty = '619'  taxct = 'TEV' )
                        ( taxty = '620'  taxct = 'TEV' )
                        ( taxty = '621'  taxct = 'TEV' )
                        ( taxty = '622'  taxct = 'TEV' )
                        ( taxty = '623'  taxct = 'TEV' )
                        ( taxty = '624'  taxct = 'TEV' )
                        ( taxty = '625'  taxct = 'TEV' )
                        ( taxty = '626'  taxct = 'TEV' )
                        ( taxty = '650'  taxct = 'TEV' )
                        ( taxty = '8001' taxct = 'DGR' )
                        ( taxty = '8002' taxct = 'DGR' )
                        ( taxty = '8004' taxct = 'DGR' )
                        ( taxty = '8005' taxct = 'DGR' )
                        ( taxty = '8006' taxct = 'DGR' )
                        ( taxty = '8007' taxct = 'DGR' )
                        ( taxty = '8008' taxct = 'DGR' )
                        ( taxty = '9021' taxct = 'DGR' )
                        ( taxty = '9040' taxct = 'DGR' )
                        ( taxty = '9077' taxct = 'OTV' )
                        ( taxty = '9944' taxct = 'DGR' ) ).

    lt_texts = VALUE #( ( taxty = '0003' spras = 'T' ltext = 'GELİR VERGİSİ STOPAJI' stext = 'GV STOPAJI' )
                        ( taxty = '0011' spras = 'T' ltext = 'KURUMLAR VERGİSİ STOPAJI' stext = 'KV STOPAJI' )
                        ( taxty = '0015' spras = 'T' ltext = 'GERÇEK USULDE KATMA DEĞER VERGİSİ' stext = 'KDV' )
                        ( taxty = '0021' spras = 'T' ltext = 'BANKA MUAMELELERİ VERGİSİ' stext = 'BMV' )
                        ( taxty = '0061' spras = 'T' ltext = 'KAYNAK KULLANIMI DESTEKLEME FONU KESİNTİSİ' stext = 'KKDF KESİNTİ' )
                        ( taxty = '0071' spras = 'T' ltext = 'PETROL VE DOĞALGAZ ÜRÜNLERİNE İLİŞKİN ÖZEL TÜKETİM VERGİSİ' stext = 'ÖTV 1.LİSTE' )
                        ( taxty = '0073' spras = 'T' ltext = 'KOLALI GAZOZ, ALKOLLÜ İÇEÇEKLER VE TÜTÜN MAMÜLLERİNE İLİŞKİN ÖZEL TÜKETİM VERGİSİ' stext = 'ÖTV 3.LİSTE' )
                        ( taxty = '0074' spras = 'T' ltext = 'DAYANIKLI TÜKETİM VE DİĞER MALLARA İLİŞKİN ÖZEL TÜKETİM VERGİSİ' stext = 'ÖTV 4.LİSTE' )
                        ( taxty = '0075' spras = 'T' ltext = 'ALKOLLÜ İÇEÇEKLERE İLİŞKİN ÖZEL TÜKETİM VERGİSİ' stext = 'ÖTV 3A LİSTE' )
                        ( taxty = '0076' spras = 'T' ltext = 'TÜTÜN MAMÜLLERİNE İLİŞKİN ÖZEL TÜKETİM VERGİSİ' stext = 'ÖTV 3B LİSTE' )
                        ( taxty = '0077' spras = 'T' ltext = 'KOLALI GAZOZLARA İLİŞKİN ÖZEL TÜKETİM VERGİSİ' stext = 'ÖTV 3C LİSTE' )
                        ( taxty = '1047' spras = 'T' ltext = 'DAMGA VERGİSİ' stext = 'DAMGA V' )
                        ( taxty = '1048' spras = 'T' ltext = '5035 SAYILI KANUNA GÖRE DAMGA VERGİSİ' stext = '5035 SK DAMGA V' )
                        ( taxty = '4071' spras = 'T' ltext = 'ELEKTRİK VE HAVAGAZI TÜKETİM VERGİSİ' stext = 'ELK.HAVAGAZ.TÜK.VER.' )
                        ( taxty = '4080' spras = 'T' ltext = 'ÖZEL İLETİŞİM VERGİSİ' stext = 'Ö.İLETİŞİM V' )
                        ( taxty = '4081' spras = 'T' ltext = '5035 SAYILI KANUNA GÖRE ÖZEL İLETİŞİM VERGİSİ' stext = '5035ÖZİLETV.' )
                        ( taxty = '4171' spras = 'T' ltext = 'PETROL VE DOĞALGAZ ÜRÜNLERİNE İLİŞKİN ÖTV TEVKİFATI' stext = 'PTR-DGZ ÖTV TEVKİFAT' )
                        ( taxty = '601'  spras = 'T' ltext = 'YAPIM İŞLERİ İLE BU İŞLERLE BİRLİKTE İFA EDİLEN MÜHENDİSLİK-MİMARLIK VE ETÜT-PROJE HİZMETLERİ' stext = 'GT 117-Bölüm (3.2.1) 4/10' )
                        ( taxty = '602'  spras = 'T' ltext = 'ETÜT, PLAN-PROJE, DANIŞMANLIK, DENETİM VE BENZERİ HİZMETLER' stext = 'GT 117-Bölüm (3.2.2) 9/10' )
                        ( taxty = '603'  spras = 'T' ltext = 'MAKİNE, TEÇHİZAT, DEMİRBAŞ VE TAŞITLARA AİT TADİL, BAKIM VE ONARIM HİZMETLERİ' stext = 'GT 117-Bölüm (3.2.3) 7/10' )
                        ( taxty = '604'  spras = 'T' ltext = 'YEMEK SERVİS HİZMETİ' stext = 'GT 117-Bölüm (3.2.4) 5/10' )
                        ( taxty = '605'  spras = 'T' ltext = 'ORGANİZASYON HİZMETİ' stext = 'GT 117-Bölüm (3.2.4) 5/10' )
                        ( taxty = '606'  spras = 'T' ltext = 'İŞGÜCÜ TEMİN HİZMETLERİ' stext = 'GT 117-Bölüm (3.2.5) 9/10' )
                        ( taxty = '607'  spras = 'T' ltext = 'ÖZEL GÜVENLİK HİZMETİ' stext = 'GT 117-Bölüm (3.2.5) 9/10' )
                        ( taxty = '608'  spras = 'T' ltext = 'YAPI DENETİM HİZMETLERİ' stext = 'GT 117-Bölüm (3.2.6) 9/10' )
                        ( taxty = '609'  spras = 'T' ltext = 'FASON OLARAK YAPTIRILAN TEKSTİL VE KONFEKSİYON İŞLERİ, ÇANTA VE AYAKKABI DİKİM İŞLERİ VE BU İŞLERE ARACILIK HİZMETLERİ' stext = 'GT 117-Bölüm (3.2.7) 7/10' )
                        ( taxty = '610'  spras = 'T' ltext = 'TURİSTİK MAĞAZALARA VERİLEN MÜŞTERİ BULMA / GÖTÜRME HİZMETLERİ' stext = 'GT 117-Bölüm (3.2.8) 9/10' )
                        ( taxty = '611'  spras = 'T' ltext = 'SPOR KULÜPLERİNİN YAYIN, REKLÂM VE İSİM HAKKI GELİRLERİNE KONU İŞLEMLERİ' stext = 'GT 117-Bölüm (3.2.9) 9/10' )
                        ( taxty = '612'  spras = 'T' ltext = 'TEMİZLİK HİZMETİ' stext = 'GT 117-Bölüm (3.2.10) 9/10' )
                        ( taxty = '613'  spras = 'T' ltext = 'ÇEVRE VE BAHÇE BAKIM HİZMETLERİ' stext = 'GT 117-Bölüm (3.2.10) 9/10' )
                        ( taxty = '614'  spras = 'T' ltext = 'SERVİS TAŞIMACILIĞI HİZMETİ' stext = 'GT 117-Bölüm (3.2.11) 5/10' )
                        ( taxty = '615'  spras = 'T' ltext = 'HER TÜRLÜ BASKI VE BASIM HİZMETLERİ' stext = 'GT 117-Bölüm (3.2.12) 7/10' )
                        ( taxty = '616'  spras = 'T' ltext = '5018 SAYILI KANUNA EKLİ CETVELLERDEKİ İDARE, KURUM VE KURUŞLARA YAPILAN DİĞER HİZMETLER' stext = 'GT 117-Bölüm (3.2.13) 5/10' )
                        ( taxty = '617'  spras = 'T' ltext = 'HURDA METALDEN ELDE EDİLEN KÜLÇE TESLİMLERİ' stext = 'GT 117-Bölüm (3.3.1) 7/10' )
                        ( taxty = '618'  spras = 'T' ltext = 'HURDA METALDEN ELDE EDİLENLER DIŞINDAKİ BAKIR, ÇİNKO VE ALÜMİNYUM KÜLÇE TESLİMLERİ' stext = 'GT 117-Bölüm (3.3.1) 7/10' )
                        ( taxty = '619'  spras = 'T' ltext = 'BAKIR, ÇİNKO VE ALÜMİNYUM ÜRÜNLERİNİN TESLİMİ' stext = 'GT 117-Bölüm (3.3.2) 5/10' )
                        ( taxty = '620'  spras = 'T' ltext = 'İSTİSNADAN VAZGEÇENLERİN HURDA VE ATIK TESLİMİ' stext = 'GT 117-Bölüm (3.3.3) 7/10' )
                        ( taxty = '621'  spras = 'T' ltext = 'METAL, PLASTİK, LASTİK, KAUÇUK, KÂĞIT VE CAM HURDA VE ATIKLARDAN ELDE EDİLEN HAMMADDE TESLİMİ' stext = 'GT 117-Bölüm (3.3.4) 9/10' )
                        ( taxty = '622'  spras = 'T' ltext = 'PAMUK, TİFTİK, YÜN VE YAPAĞI İLE HAM POST VE DERİ TESLİMLERİ' stext = 'GT 117-Bölüm (3.3.5) 9/10' )
                        ( taxty = '623'  spras = 'T' ltext = 'AĞAÇ VE ORMAN ÜRÜNLERİ TESLİMİ' stext = 'GT 117-Bölüm (3.3.6) 5/10' )
                        ( taxty = '624'  spras = 'T' ltext = 'YÜK TAŞIMACILIĞI HİZMETİ' )
                        ( taxty = '625'  spras = 'T' ltext = 'TİCARİ REKLAM HİZMETLERİ' )
                        ( taxty = '626'  spras = 'T' ltext = 'DİĞER TESLİMLER' )
                        ( taxty = '650'  spras = 'T' ltext = 'DİĞERLERİ' stext = 'DİĞERLERİ 2/10,5/10, 7/10,9/10' )
                        ( taxty = '8001' spras = 'T' ltext = 'BORSA TESCİL ÜCRETİ' stext = 'BORSA TES.ÜC.' )
                        ( taxty = '8002' spras = 'T' ltext = 'ENERJİ FONU' stext = 'ENERJİ FONU' )
                        ( taxty = '8004' spras = 'T' ltext = 'TRT PAYI' stext = 'TRT PAYI' )
                        ( taxty = '8005' spras = 'T' ltext = 'ELEKTRİK TÜKETİM VERGİSİ' stext = 'ELK.TÜK.VER.' )
                        ( taxty = '8006' spras = 'T' ltext = 'TELSİZ KULLANIM ÜCRETİ' stext = 'TK KULLANIM' )
                        ( taxty = '8007' spras = 'T' ltext = 'TELSİZ RUHSAT ÜCRETİ' stext = 'TK RUHSAT' )
                        ( taxty = '8008' spras = 'T' ltext = 'ÇEVRE TEMİZLİK VERGİSİ' stext = 'ÇEV. TEM .VER.' )
                        ( taxty = '9021' spras = 'T' ltext = '4961 BANKA SİGORTA MUAMELELERİ VERGİSİ' stext = '4961 BANKA SMV' )
                        ( taxty = '9040' spras = 'T' ltext = 'MERA FONU' stext = 'MERA FONU' )
                        ( taxty = '9077' spras = 'T' ltext = 'MOTORLU TAŞIT ARAÇLARINA İLİŞKİN ÖZEL TÜKETİM VERGİSİ (TESCİLE TABİ OLANLAR)' stext = 'ÖTV 2.LİSTE' )
                        ( taxty = '9944' spras = 'T' ltext = 'BELEDİYELERE ÖDENEN HAL RÜSUMU' stext = 'BEL.ÖD.HAL RÜSUM' ) ).
    LOOP AT lt_texts INTO DATA(ls_text).
      CHECK ls_text-spras = 'T'.
      ls_text-spras = 'E'.
      APPEND ls_text TO lt_texts.
    ENDLOOP.

    DELETE FROM zetr_t_taxcd.
    DELETE FROM zetr_t_taxcx.
    COMMIT WORK AND WAIT.

    INSERT zetr_t_taxcd FROM TABLE @lt_codes.
    INSERT zetr_t_taxcx FROM TABLE @lt_texts.
    COMMIT WORK AND WAIT.
  ENDMETHOD.