INTERFACE zif_etr_delivery_ubl21
  PUBLIC .

  INTERFACES:
    zif_etr_common_ubl21.

  ALIASES:
    IdentifierType        FOR zif_etr_common_ubl21~IdentifierType,
    IndicatorType         FOR zif_etr_common_ubl21~IndicatorType,
    DateType              FOR zif_etr_common_ubl21~DateType,
    TimeType              FOR zif_etr_common_ubl21~TimeType,
    CodeType              FOR zif_etr_common_ubl21~CodeType,
    TextType              FOR zif_etr_common_ubl21~TextType,
    NumericType           FOR zif_etr_common_ubl21~NumericType,
    OrderReferenceType    FOR zif_etr_common_ubl21~OrderReferenceType,
    DocumentReferenceType FOR zif_etr_common_ubl21~DocumentReferenceType,
    SignatureType         FOR zif_etr_common_ubl21~SignatureType,
    CustomerPartyType     FOR zif_etr_common_ubl21~CustomerPartyType,
    SupplierPartyType     FOR zif_etr_common_ubl21~SupplierPartyType,
    DespatchLineType      FOR zif_etr_common_ubl21~DespatchLineType,
    ReceiptLineType       FOR zif_etr_common_ubl21~ReceiptLineType,
    ShipmentType          FOR zif_etr_common_ubl21~ShipmentType,
    UBLExtensionsType     FOR zif_etr_common_ubl21~UBLExtensionsType.

  TYPES:
    BEGIN OF DespatchAdviceType,
      UBLExtensions               TYPE UBLExtensionsType,
      UBLVersionID                TYPE IdentifierType,
      CustomizationID             TYPE IdentifierType,
      ProfileID                   TYPE IdentifierType,
      Id                          TYPE IdentifierType,
      CopyIndicator               TYPE IndicatorType,
      UUId                        TYPE IdentifierType,
      IssueDate                   TYPE DateType,
      IssueTime                   TYPE TimeType,
      DespatchAdviceTypeCode      TYPE CodeType,
      Note                        TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      LineCountNumeric            TYPE NumericType,
      OrderReference              TYPE STANDARD TABLE OF OrderReferenceType WITH EMPTY KEY,
      AdditionalDocumentReference TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      Signature                   TYPE STANDARD TABLE OF SignatureType WITH EMPTY KEY,
      DespatchSupplierParty       TYPE SupplierPartyType,
      DeliveryCustomerParty       TYPE CustomerPartyType,
      BuyerCustomerParty          TYPE CustomerPartyType,
      SellerSupplierParty         TYPE SupplierPartyType,
      OriginatorCustomerParty     TYPE CustomerPartyType,
      Shipment                    TYPE ShipmentType,
      DespatchLine                TYPE STANDARD TABLE OF DespatchLineType WITH EMPTY KEY,
    END OF DespatchAdviceType,

    BEGIN OF ReceiptAdviceType,
      UBLExtensions               TYPE UBLExtensionsType,
      UBLVersionID                TYPE IdentifierType,
      CustomizationID             TYPE IdentifierType,
      ProfileID                   TYPE IdentifierType,
      Id                          TYPE IdentifierType,
      CopyIndicator               TYPE IndicatorType,
      UUId                        TYPE IdentifierType,
      IssueDate                   TYPE DateType,
      IssueTime                   TYPE TimeType,
      ReceiptAdviceTypeCode       TYPE CodeType,
      Note                        TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      LineCountNumeric            TYPE NumericType,
      OrderReference              TYPE STANDARD TABLE OF OrderReferenceType WITH EMPTY KEY,
      DespatchDocumentReference   TYPE DocumentReferenceType,
      AdditionalDocumentReference TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      Signature                   TYPE STANDARD TABLE OF SignatureType WITH EMPTY KEY,
      DeliveryCustomerParty       TYPE CustomerPartyType,
      DespatchSupplierParty       TYPE SupplierPartyType,
      BuyerCustomerParty          TYPE CustomerPartyType,
      SellerSupplierParty         TYPE SupplierPartyType,
      Shipment                    TYPE ShipmentType,
      ReceiptLine                 TYPE STANDARD TABLE OF ReceiptLineType WITH EMPTY KEY,
    END OF ReceiptAdviceType.
ENDINTERFACE.