INTERFACE zif_etr_common_ubl21
  PUBLIC .
  TYPES:
    BEGIN OF AmountType,
      currencyID                TYPE string,
      currencyCodeListVersionID TYPE string,
      content                   TYPE string,
    END OF AmountType,

    BEGIN OF BinaryObjectType,
      format           TYPE string,
      mimeCode         TYPE string,
      encodingCode     TYPE string,
      characterSetCode TYPE string,
      uri              TYPE string,
      filename         TYPE string,
      content          TYPE string,
    END OF BinaryObjectType,

    BEGIN OF CodeType,
      listID         TYPE string,
      listAgencyID   TYPE string,
      listAgencyName TYPE string,
      listName       TYPE string,
      listVersionID  TYPE string,
      name           TYPE string,
      languageID     TYPE string,
      listURI        TYPE string,
      listSchemeURI  TYPE string,
      content        TYPE string,
    END OF CodeType,

    BEGIN OF DateTimeType,
      format  TYPE string,
      content TYPE string,
    END OF DateTimeType,

    BEGIN OF IdentifierType,
      schemeID         TYPE string,
      schemeName       TYPE string,
      schemeAgencyID   TYPE string,
      schemeAgencyName TYPE string,
      schemeVersionID  TYPE string,
      schemeDataURI    TYPE string,
      schemeURI        TYPE string,
      content          TYPE string,
    END OF IdentifierType,

    BEGIN OF IndicatorType,
      content TYPE string,
    END OF IndicatorType,

    BEGIN OF MeasureType,
      unitCode              TYPE string,
      unitCodeListVersionID TYPE string,
      content               TYPE string,
    END OF MeasureType,

    BEGIN OF NumericType,
      format  TYPE string,
      content TYPE string,
    END OF NumericType,

    BEGIN OF QuantityType,
      unitCode               TYPE string,
      unitCodeListID         TYPE string,
      unitCodeListAgencyID   TYPE string,
      unitCodeListAgencyName TYPE string,
      content                TYPE string,
    END OF QuantityType,

    BEGIN OF TextType,
      languageID       TYPE string,
      languageLocaleID TYPE string,
      content          TYPE string,
    END OF TextType,

    BEGIN OF DateType,
      content TYPE string,
    END OF DateType,

    BEGIN OF TimeType,
      content TYPE string,
    END OF TimeType,

    BEGIN OF ExtensionContentType,
      any TYPE xsdany,
    END OF ExtensionContentType,

    BEGIN OF UBLExtensionType,
      ExtensionContent TYPE ExtensionContentType,
    END OF UBLExtensionType,

    BEGIN OF UBLExtensionsType,
      UBLExtension TYPE STANDARD TABLE OF UBLExtensionType WITH EMPTY KEY,
    END OF UBLExtensionsType,

    BEGIN OF PeriodType,
      StartDate       TYPE DateType,
      StartTime       TYPE TimeType,
      EndDate         TYPE DateType,
      EndTime         TYPE TimeType,
      DurationMeasure TYPE MeasureType,
      Description     TYPE TextType,
    END OF PeriodType,

    BEGIN OF ExternalReferenceType,
      uri TYPE IdentifierType,
    END OF ExternalReferenceType,

    BEGIN OF AttachmentType,
      EmbeddedDocumentBinaryObject TYPE BinaryObjectType,
      ExternalReference            TYPE ExternalReferenceType,
    END OF AttachmentType,

    BEGIN OF AddressType,
      Id                  TYPE IdentifierType,
      Postbox             TYPE TextType,
      Room                TYPE TextType,
      StreetName          TYPE TextType,
      BlockName           TYPE TextType,
      BuildingName        TYPE TextType,
      BuildingNumber      TYPE TextType,
      CitySubdivisionName TYPE TextType,
      CityName            TYPE TextType,
      PostalZone          TYPE TextType,
      Region              TYPE TextType,
      District            TYPE TextType,
      Country             TYPE TextType,
    END OF AddressType,

    BEGIN OF LocationType,
      Id      TYPE IdentifierType,
      Address TYPE AddressType,
    END OF LocationType,

    BEGIN OF TaxSchemeType,
      Id          TYPE IdentifierType,
      Name        TYPE TextType,
      TaxTypeCode TYPE CodeType,
    END OF TaxSchemeType,

    BEGIN OF PartyTaxSchemeType,
      RegistrationName TYPE TextType,
      CompanyID        TYPE IdentifierType,
      TaxScheme        TYPE TaxSchemeType,
    END OF PartyTaxSchemeType,

    BEGIN OF CorporateRegistrationSchemeTyp,
      Id                            TYPE IdentifierType,
      Name                          TYPE TextType,
      CorporateRegistrationTypeCode TYPE CodeType,
      JurisdictionRegionAddress     TYPE STANDARD TABLE OF AddressType WITH EMPTY KEY,
    END OF CorporateRegistrationSchemeTyp,

    BEGIN OF CommunicationType,
      ChannelCode TYPE CodeType,
      Channel     TYPE TextType,
      Value       TYPE TextType,
    END OF CommunicationType,

    BEGIN OF ContactType,
      Id                 TYPE IdentifierType,
      Name               TYPE TextType,
      Telephone          TYPE TextType,
      Telefax            TYPE TextType,
      ElectronicMail     TYPE TextType,
      Note               TYPE TextType,
      OtherCommunication TYPE STANDARD TABLE OF CommunicationType WITH EMPTY KEY,
    END OF ContactType,

    BEGIN OF DocumentReferenceType,
      Id                  TYPE IdentifierType,
      IssueDate           TYPE DateType,
      DocumentTypeCode    TYPE CodeType,
      DocumentType        TYPE TextType,
      DocumentDescription TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      Attachment          TYPE AttachmentType,
      ValidityPeriod      TYPE PeriodType,
      IssuerParty         TYPE xsdany, "Revised
    END OF DocumentReferenceType,

    BEGIN OF FinancialInstitutionType,
      Name TYPE TextType,
    END OF FinancialInstitutionType,

    BEGIN OF BranchType,
      Name                 TYPE TextType,
      FinancialInstitution TYPE FinancialInstitutionType,
    END OF BranchType,

    BEGIN OF FinancialAccountType,
      Id                         TYPE IdentifierType,
      CurrencyCode               TYPE CodeType,
      PaymentNote                TYPE TextType,
      FinancialInstitutionBranch TYPE BranchType,
    END OF FinancialAccountType,

    BEGIN OF PersonType,
      FirstName                 TYPE TextType,
      FamilyName                TYPE TextType,
      Title                     TYPE TextType,
      MiddleName                TYPE TextType,
      NameSuffix                TYPE TextType,
      NationalityID             TYPE IdentifierType,
      FinancialAccount          TYPE FinancialAccountType,
      IdentityDocumentReference TYPE DocumentReferenceType,
    END OF PersonType,

    BEGIN OF zPartyType,
      WebsiteURI                 TYPE IdentifierType,
      EndpointID                 TYPE IdentifierType,
      IndustryClassificationCode TYPE CodeType,
      PartyIdentification        TYPE STANDARD TABLE OF IdentifierType WITH EMPTY KEY,
      PartyName                  TYPE TextType,
      PostalAddress              TYPE AddressType,
      PhysicalLocation           TYPE LocationType,
      PartyTaxScheme             TYPE PartyTaxSchemeType,
      PartyLegalEntity           TYPE xsdany, "Revised
      Contact                    TYPE ContactType,
      Person                     TYPE PersonType,
      AgentParty                 TYPE xsdany, "Revised
    END OF zPartyType,

    BEGIN OF PartyLegalEntityType,
      RegistrationName            TYPE TextType,
      CompanyID                   TYPE IdentifierType,
      RegistrationDate            TYPE DateType,
      SoleProprietorshipIndicator TYPE IndicatorType,
      CorporateStockAmount        TYPE AmountType,
      FullyPaidSharesIndicator    TYPE IndicatorType,
      CorporateRegistrationScheme TYPE CorporateRegistrationSchemeTyp,
      HeadOfficeParty             TYPE zPartyType, "Revised
    END OF PartyLegalEntityType,

    BEGIN OF PartyType,
      WebsiteURI                 TYPE IdentifierType,
      EndpointID                 TYPE IdentifierType,
      IndustryClassificationCode TYPE CodeType,
      PartyIdentification        TYPE STANDARD TABLE OF IdentifierType WITH EMPTY KEY,
      PartyName                  TYPE TextType,
      PostalAddress              TYPE AddressType,
      PhysicalLocation           TYPE LocationType,
      PartyTaxScheme             TYPE PartyTaxSchemeType,
      PartyLegalEntity           TYPE STANDARD TABLE OF PartyLegalEntityType WITH EMPTY KEY,
      Contact                    TYPE ContactType,
      Person                     TYPE PersonType,
      AgentParty                 TYPE zPartyType, "Revised
    END OF PartyType,

    BEGIN OF OrderReferenceType,
      Id                TYPE IdentifierType,
      SalesOrderID      TYPE IdentifierType,
      IssueDate         TYPE DateType,
      OrderTypeCode     TYPE CodeType,
      DocumentReference TYPE DocumentReferenceType,
    END OF OrderReferenceType,

    BEGIN OF AllowanceChargeType,
      ChargeIndicator         TYPE IndicatorType,
      AllowanceChargeReason   TYPE TextType,
      MultiplierFactorNumeric TYPE NumericType,
      SequenceNumeric         TYPE NumericType,
      Amount                  TYPE AmountType,
      BaseAmount              TYPE AmountType,
      PerUnitAmount           TYPE AmountType,
    END OF AllowanceChargeType,

    BEGIN OF BillingReferenceLineType,
      Id              TYPE IdentifierType,
      Amount          TYPE AmountType,
      AllowanceCharge TYPE STANDARD TABLE OF AllowanceChargeType WITH EMPTY KEY,
    END OF BillingReferenceLineType,

    BEGIN OF BillingReferenceType,
      InvoiceDocumentReference       TYPE DocumentReferenceType,
      SelfBilledInvoiceDocumentRefer TYPE DocumentReferenceType,
      CreditNoteDocumentReference    TYPE DocumentReferenceType,
      SelfBilledCreditNoteDocumentRe TYPE DocumentReferenceType,
      DebitNoteDocumentReference     TYPE DocumentReferenceType,
      ReminderDocumentReference      TYPE DocumentReferenceType,
      AdditionalDocumentReference    TYPE DocumentReferenceType,
      BillingReferenceLine           TYPE STANDARD TABLE OF BillingReferenceLineType WITH EMPTY KEY,
    END OF BillingReferenceType,

    BEGIN OF SignatureType,
      Id                         TYPE IdentifierType,
      SignatoryParty             TYPE PartyType,
      DigitalSignatureAttachment TYPE AttachmentType,
    END OF SignatureType,

    BEGIN OF SupplierPartyType,
      Party           TYPE PartyType,
      DespatchContact TYPE ContactType,
    END OF SupplierPartyType,

    BEGIN OF CustomerPartyType,
      Party           TYPE PartyType,
      DeliveryContact TYPE ContactType,
    END OF CustomerPartyType,

    BEGIN OF PaymentMeansType,
      PaymentMeansCode      TYPE CodeType,
      PaymentDueDate        TYPE DateType,
      PaymentChannelCode    TYPE CodeType,
      InstructionNote       TYPE TextType,
      PayerFinancialAccount TYPE FinancialAccounTType,
      PayeeFinancialAccount TYPE FinancialAccounTType,
    END OF PaymentMeansType,

    BEGIN OF PaymentTermsType,
      Note                    TYPE TextType,
      PenaltySurchargePercent TYPE NumericType,
      Amount                  TYPE AmountType,
      PenaltyAmount           TYPE AmountType,
      PaymentDueDate          TYPE DateType,
      SettlementPeriod        TYPE PeriodType,
    END OF PaymentTermsType,

    BEGIN OF ExchangeRateType,
      SourceCurrencyCode TYPE CodeType,
      TargetCurrencyCode TYPE CodeType,
      CalculationRate    TYPE NumericType,
      Date               TYPE DateType,
    END OF ExchangeRateType,

    BEGIN OF TaxCategoryType,
      Name                   TYPE TextType,
      TaxExemptionReasonCode TYPE CodeType,
      TaxExemptionReason     TYPE TextType,
      TaxScheme              TYPE TaxSchemeType,
    END OF TaxCategoryType,

    BEGIN OF TaxSubtotalType,
      TaxableAmount                TYPE AmountType,
      TaxAmount                    TYPE AmountType,
      CalculationSequenceNumeric   TYPE NumericType,
      TransactionCurrencyTaxAmount TYPE AmountType,
      Percent                      TYPE NumericType,
      BaseUnitMeasure              TYPE MeasureType,
      PerUnitAmount                TYPE AmountType,
      TaxCategory                  TYPE TaxCategoryType,
    END OF TaxSubtotalType,

    BEGIN OF TaxTotalType,
      TaxAmount   TYPE AmountType,
      TaxSubtotal TYPE STANDARD TABLE OF TaxSubtotalType WITH EMPTY KEY,
    END OF TaxTotalType,

    BEGIN OF MonetaryTotalType,
      LineExtensionAmount   TYPE AmountType,
      TaxExclusiveAmount    TYPE AmountType,
      TaxInclusiveAmount    TYPE AmountType,
      AllowanceTotalAmount  TYPE AmountType,
      ChargeTotalAmount     TYPE AmountType,
      PayableRoundingAmount TYPE AmountType,
      PayableAmount         TYPE AmountType,
    END OF MonetaryTotalType,

    BEGIN OF OrderLineReferenceType,
      LineID           TYPE IdentifierType,
      SalesOrderLineID TYPE IdentifierType,
      UUId             TYPE IdentifierType,
      LineStatusCode   TYPE CodeType,
      OrderReference   TYPE OrderReferenceType,
    END OF OrderLineReferenceType,

    BEGIN OF LineReferenceType,
      LineID            TYPE IdentifierType,
      LineStatusCode    TYPE CodeType,
      DocumentReference TYPE DocumentReferenceType,
    END OF LineReferenceType,

    BEGIN OF ItemIdentificationType,
      Id TYPE IdentifierType,
    END OF ItemIdentificationType,

    BEGIN OF CountryType,
      IdentificationCode TYPE CodeType,
      Name               TYPE TextType,
    END OF CountryType,

    BEGIN OF CommodityClassificationType,
      ItemClassificationCode TYPE CodeType,
    END OF CommodityClassificationType,

    BEGIN OF ItemPropertyGroupType,
      Id             TYPE IdentifierType,
      Name           TYPE TextType,
      ImportanceCode TYPE CodeType,
    END OF ItemPropertyGroupType,

    BEGIN OF ItemPropertyRangeType,
      MinimumValue TYPE TextType,
      MaximumValue TYPE TextType,
    END OF ItemPropertyRangeType,

    BEGIN OF DimensionType,
      AttributeID    TYPE IdentifierType,
      Measure        TYPE MeasureType,
      Description    TYPE TextType,
      MinimumMeasure TYPE MeasureType,
      MaximumMeasure TYPE MeasureType,
    END OF DimensionType,

    BEGIN OF ItemPropertyType,
      Id                TYPE IdentifierType,
      Name              TYPE TextType,
      NameCode          TYPE CodeType,
      TestMethod        TYPE TextType,
      Value             TYPE TextType,
      ValueQuantity     TYPE QuantityType,
      ValueQualifier    TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      ImportanceCode    TYPE CodeType,
      ListValue         TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      UsabilityPeriod   TYPE PeriodType,
      ItemPropertyGroup TYPE STANDARD TABLE OF ItemPropertyGroupType WITH EMPTY KEY,
      RangeDimension    TYPE DimensionType,
      ItemPropertyRange TYPE STANDARD TABLE OF ItemPropertyRangeType WITH EMPTY KEY,
    END OF ItemPropertyType,

    BEGIN OF LotIdentificationType,
      LotNumberID            TYPE IdentifierType,
      ExpiryDate             TYPE DateType,
      AdditionalItemProperty TYPE STANDARD TABLE OF ItemPropertyType WITH EMPTY KEY,
    END OF LotIdentificationType,

    BEGIN OF ItemInstanceType,
      ProductTraceID         TYPE IdentifierType,
      ManufactureDate        TYPE DateType,
      ManufactureTime        TYPE TimeType,
      BestBeforeDate         TYPE DateType,
      RegistrationID         TYPE IdentifierType,
      SerialID               TYPE IdentifierType,
      AdditionalItemProperty TYPE STANDARD TABLE OF ItemPropertyType WITH EMPTY KEY,
      LotIdentification      TYPE LotIdentificationType,
    END OF ItemInstanceType,

    BEGIN OF ItemType,
      Description                    TYPE TextType,
      Name                           TYPE TextType,
      Keyword                        TYPE TextType,
      BrandName                      TYPE TextType,
      ModelName                      TYPE TextType,
      BuyersItemIdentification       TYPE ItemIdentificationType,
      SellersItemIdentification      TYPE ItemIdentificationType,
      ManufacturersItemIdentificatio TYPE ItemIdentificationType,
      AdditionalItemIdentification   TYPE STANDARD TABLE OF ItemIdentificationType WITH EMPTY KEY,
      OriginCountry                  TYPE CountryType,
      CommodityClassification        TYPE CommodityClassificationType,
      ItemInstance                   TYPE STANDARD TABLE OF ItemInstanceType WITH EMPTY KEY,
    END OF ItemType,

    BEGIN OF PriceType,
      PriceAmount TYPE AmountType,
    END OF PriceType,

    BEGIN OF zInvoiceLineType,
      Id                    TYPE IdentifierType,
      Note                  TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      InvoicedQuantity      TYPE QuantityType,
      LineExtensionAmount   TYPE AmountType,
      OrderLineReference    TYPE STANDARD TABLE OF OrderLineReferenceType WITH EMPTY KEY,
      DespatchLineReference TYPE STANDARD TABLE OF LineReferenceType WITH EMPTY KEY,
      ReceiptLineReference  TYPE STANDARD TABLE OF LineReferenceType WITH EMPTY KEY,
      Delivery              TYPE xsdany, "Revised
      AllowanceCharge       TYPE STANDARD TABLE OF AllowanceChargeType WITH EMPTY KEY,
      TaxTotal              TYPE TaxTotalType,
      WithholdingTaxTotal   TYPE STANDARD TABLE OF TaxTotalType WITH EMPTY KEY,
      Item                  TYPE ItemType,
      Price                 TYPE PriceType,
      SubInvoiceLine        TYPE xsdany, "Revised
    END OF zInvoiceLineType,

    BEGIN OF StowageType,
      LocationID           TYPE IdentifierType,
      Location             TYPE TextType,
      MeasurementDimension TYPE DimensionType,
    END OF StowageType,

    BEGIN OF RailTransportType,
      TrainID   TYPE IdentifierType,
      RailCarID TYPE IdentifierType,
    END OF RailTransportType,

    BEGIN OF AirTransportType,
      AircraftID TYPE IdentifierType,
    END OF AirTransportType,

    BEGIN OF RoadTransportType,
      LicensePlateID TYPE IdentifierType,
    END OF RoadTransportType,

    BEGIN OF MaritimeTransport,
      VesselID                       TYPE IdentifierType,
      VesselName                     TYPE TextType,
      RadioCallSignID                TYPE IdentifierType,
      ShipsRequirements              TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      GrossTonnageMeasure            TYPE MeasureType,
      NetTonnageMeasure              TYPE MeasureType,
      RegistryCertificateDocumentRef TYPE DocumentReferenceType,
      RegistryPortLocation           TYPE LocationType,
    END OF MaritimeTransport,

    BEGIN OF TransportMeansType,
      JourneyID                 TYPE IdentifierType,
      RegistrationNationalityID TYPE IdentifierType,
      RegistrationNationality   TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      DirectionCode             TYPE CodeType,
      TransportMeansTypeCode    TYPE CodeType,
      TradeServiceCode          TYPE CodeType,
      Stowage                   TYPE StowageType,
      AirTransport              TYPE AirTransportType,
      RoadTransport             TYPE RoadTransportType,
      RailTransport             TYPE RailTransportType,
      MaritimeTransport         TYPE MaritimeTransport,
      OwnerParty                TYPE PartyType,
      MeasurementDimension      TYPE STANDARD TABLE OF StowageType WITH EMPTY KEY,
    END OF TransportMeansType,

    BEGIN OF ShipmentStageType,
      Id                     TYPE IdentifierType,
      TransportModeCode      TYPE CodeType,
      TransportMeansTypeCode TYPE CodeType,
      TransitDirectionCode   TYPE CodeType,
      Instructions           TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      TransitPeriod          TYPE PeriodType,
      TransportMeans         TYPE TransportMeansType,
      DriverPerson           TYPE STANDARD TABLE OF PersonType WITH EMPTY KEY,
    END OF ShipmentStageType,

    BEGIN OF TemperatureType,
      AttributeID TYPE IdentifierType,
      Measure     TYPE MeasureType,
      Description TYPE TextType,
    END OF TemperatureType,

    BEGIN OF GoodsItemType,
      Id                             TYPE IdentifierType,
      Description                    TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      HazardousRiskIndicator         TYPE IndicatorType,
      DeclaredCustomsValueAmount     TYPE AmountType,
      DeclaredForCarriageValueAmount TYPE AmountType,
      DeclaredStatisticsValueAmount  TYPE AmountType,
      FreeOnBoardValueAmount         TYPE AmountType,
      InsuranceValueAmount           TYPE AmountType,
      ValueAmount                    TYPE AmountType,
      GrossWeightMeasure             TYPE MeasureType,
      NetWeightMeasure               TYPE MeasureType,
      ChargeableWeightMeasure        TYPE MeasureType,
      GrossVolumeMeasure             TYPE MeasureType,
      NetVolumeMeasure               TYPE MeasureType,
      Quantity                       TYPE QuantityType,
      RequiredCustomsID              TYPE IdentifierType,
      CustomsStatusCode              TYPE CodeType,
      CustomsTariffQuantity          TYPE QuantityType,
      CustomsImportClassifiedIndicat TYPE IndicatorType,
      ChargeableQuantity             TYPE QuantityType,
      ReturnableQuantity             TYPE QuantityType,
      TraceID                        TYPE IdentifierType,
      Item                           TYPE STANDARD TABLE OF ItemType WITH EMPTY KEY,
      FreightAllowanceCharge         TYPE STANDARD TABLE OF AllowanceChargeType WITH EMPTY KEY,
      InvoiceLine                    TYPE STANDARD TABLE OF zInvoiceLineType WITH EMPTY KEY,
      Temperature                    TYPE STANDARD TABLE OF TemperatureType WITH EMPTY KEY,
      OriginAddress                  TYPE AddressType,
      MeasurementDimension           TYPE STANDARD TABLE OF DimensionType WITH EMPTY KEY,
    END OF GoodsItemType,

    BEGIN OF PackageType,
      Id                          TYPE IdentifierType,
      Quantity                    TYPE QuantityType,
      ReturnableMaterialIndicator TYPE IndicatorType,
      PackageLevelCode            TYPE CodeType,
      PackagingTypeCode           TYPE CodeType,
      PackingMaterial             TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      ContainedPackage            TYPE xsdany, "Revised
      GoodsItem                   TYPE STANDARD TABLE OF GoodsItemType WITH EMPTY KEY,
      MeasurementDimension        TYPE STANDARD TABLE OF DimensionType WITH EMPTY KEY,
    END OF PackageType,

    BEGIN OF TransportEquipmentType,
      Id                         TYPE IdentifierType,
      TransportEquipmentTypeCode TYPE CodeType,
      Description                TYPE TextType,
    END OF TransportEquipmentType,

    BEGIN OF HazardousGoodsTransitType,
      TransportEmergencyCardCode TYPE CodeType,
      PackingCriteriaCode        TYPE CodeType,
      HazardousRegulationCode    TYPE CodeType,
      InhalationToxicityZoneCode TYPE CodeType,
      TransportAuthorizationCode TYPE CodeType,
      MaximumTemperature         TYPE TemperatureType,
      MinimumTemperature         TYPE TemperatureType,
    END OF HazardousGoodsTransitType,

    BEGIN OF CustomsDeclarationType,
      Id          TYPE IdentifierType,
      IssuerParty TYPE PartyType,
    END OF CustomsDeclarationType,

    BEGIN OF TransportHandlingUnitType,
      Id                             TYPE IdentifierType,
      TransportHandlingUnitTypeCode  TYPE CodeType,
      HandlingCode                   TYPE CodeType,
      HandlingInstructions           TYPE TextType,
      HazardousRiskIndicator         TYPE IndicatorType,
      TotalGoodsItemQuantity         TYPE QuantityType,
      TotalPackageQuantity           TYPE QuantityType,
      DamageRemarks                  TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      TraceID                        TYPE IdentifierType,
      ActualPackage                  TYPE STANDARD TABLE OF PackageType WITH EMPTY KEY,
      TransportEquipment             TYPE STANDARD TABLE OF TransportEquipmentType WITH EMPTY KEY,
      TransportMeans                 TYPE STANDARD TABLE OF TransportMeansType WITH EMPTY KEY,
      HazardousGoodsTransit          TYPE STANDARD TABLE OF HazardousGoodsTransitType WITH EMPTY KEY,
      MeasurementDimension           TYPE STANDARD TABLE OF MeasureType WITH EMPTY KEY,
      MinimumTemperature             TYPE TemperatureType,
      MaximumTemperature             TYPE TemperatureType,
      FloorSpaceMeasurementDimension TYPE DimensionType,
      PalletSpaceMeasurementDimensio TYPE DimensionType,
      ShipmentDocumentReference      TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      CustomsDeclaration             TYPE STANDARD TABLE OF CustomsDeclarationType WITH EMPTY KEY,
    END OF TransportHandlingUnitType,

    BEGIN OF DeliveryTermsType,
      Id           TYPE IdentifierType,
      SpecialTerms TYPE TextType,
      Amount       TYPE AmountType,
    END OF DeliveryTermsType,

    BEGIN OF DespatchType,
      Id                      TYPE IdentifierType,
      ActualDespatchDate      TYPE DateType,
      ActualDespatchTime      TYPE TimeType,
      Instructions            TYPE TextType,
      DespatchAddress         TYPE AddressType,
      DespatchParty           TYPE PartyType,
      Contact                 TYPE ContactType,
      EstimatedDespatchPeriod TYPE PeriodType,
    END OF DespatchType,

    BEGIN OF zShipmentType,
      Id                             TYPE IdentifierType,
      HandlingCode                   TYPE CodeType,
      HandlingInstructions           TYPE TextType,
      GrossWeightMeasure             TYPE MeasureType,
      NetWeightMeasure               TYPE MeasureType,
      GrossVolumeMeasure             TYPE MeasureType,
      NetVolumeMeasure               TYPE MeasureType,
      TotalGoodsItemQuantity         TYPE QuantityType,
      TotalTransportHandlingUnitQuan TYPE QuantityType,
      InsuranceValueAmount           TYPE AmountType,
      DeclaredCustomsValueAmount     TYPE AmountType,
      DeclaredForCarriageValueAmount TYPE AmountType,
      DeclaredStatisticsValueAmount  TYPE AmountType,
      FreeOnBoardValueAmount         TYPE AmountType,
      SpecialInstructions            TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      GoodsItem                      TYPE STANDARD TABLE OF GoodsItemType WITH EMPTY KEY,
      ShipmentStage                  TYPE STANDARD TABLE OF ShipmentStageType WITH EMPTY KEY,
      Delivery                       TYPE xsdany, "Revised
      TransportHandlingUnit          TYPE STANDARD TABLE OF TransportHandlingUnitType WITH EMPTY KEY,
      ReturnAddress                  TYPE AddressType,
      FirstArrivalPortLocation       TYPE LocationType,
      LastExitPortLocation           TYPE LocationType,
    END OF zShipmentType,

    BEGIN OF DeliveryType,
      Id                          TYPE IdentifierType,
      Quantity                    TYPE QuantityType,
      ActualDeliveryDate          TYPE DateType,
      ActualDeliveryTime          TYPE TimeType,
      LatestDeliveryDate          TYPE DateType,
      LatestDeliveryTime          TYPE TimeType,
      TrackingID                  TYPE IdentifierType,
      DeliveryAddress             TYPE AddressType,
      AlternativeDeliveryLocation TYPE LocationType,
      EstimatedDeliveryPeriod     TYPE PeriodType,
      CarrierParty                TYPE PartyType,
      DeliveryParty               TYPE PartyType,
      Despatch                    TYPE DespatchType,
      DeliveryTerms               TYPE STANDARD TABLE OF DeliveryTermsType WITH EMPTY KEY,
      Shipment                    TYPE zShipmentType, "Revised
    END OF DeliveryType,

    BEGIN OF ShipmentType,
      Id                             TYPE IdentifierType,
      HandlingCode                   TYPE CodeType,
      HandlingInstructions           TYPE TextType,
      GrossWeightMeasure             TYPE MeasureType,
      NetWeightMeasure               TYPE MeasureType,
      GrossVolumeMeasure             TYPE MeasureType,
      NetVolumeMeasure               TYPE MeasureType,
      TotalGoodsItemQuantity         TYPE QuantityType,
      TotalTransportHandlingUnitQuan TYPE QuantityType,
      InsuranceValueAmount           TYPE AmountType,
      DeclaredCustomsValueAmount     TYPE AmountType,
      DeclaredForCarriageValueAmount TYPE AmountType,
      DeclaredStatisticsValueAmount  TYPE AmountType,
      FreeOnBoardValueAmount         TYPE AmountType,
      SpecialInstructions            TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      GoodsItem                      TYPE STANDARD TABLE OF GoodsItemType WITH EMPTY KEY,
      ShipmentStage                  TYPE STANDARD TABLE OF ShipmentStageType WITH EMPTY KEY,
      Delivery                       TYPE STANDARD TABLE OF DeliveryType WITH EMPTY KEY,
      TransportHandlingUnit          TYPE STANDARD TABLE OF TransportHandlingUnitType WITH EMPTY KEY,
      ReturnAddress                  TYPE AddressType,
      FirstArrivalPortLocation       TYPE LocationType,
      LastExitPortLocation           TYPE LocationType,
    END OF ShipmentType,

    BEGIN OF InvoiceLineType,
      Id                    TYPE IdentifierType,
      Note                  TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      InvoicedQuantity      TYPE QuantityType,
      LineExtensionAmount   TYPE AmountType,
      OrderLineReference    TYPE STANDARD TABLE OF OrderLineReferenceType WITH EMPTY KEY,
      DespatchLineReference TYPE STANDARD TABLE OF LineReferenceType WITH EMPTY KEY,
      ReceiptLineReference  TYPE STANDARD TABLE OF LineReferenceType WITH EMPTY KEY,
      Delivery              TYPE STANDARD TABLE OF DeliveryType WITH EMPTY KEY,
      AllowanceCharge       TYPE STANDARD TABLE OF AllowanceChargeType WITH EMPTY KEY,
      TaxTotal              TYPE TaxTotalType,
      WithholdingTaxTotal   TYPE STANDARD TABLE OF TaxTotalType WITH EMPTY KEY,
      Item                  TYPE ItemType,
      Price                 TYPE PriceType,
      SubInvoiceLine        TYPE STANDARD TABLE OF zInvoiceLineType WITH EMPTY KEY, "Revised
    END OF InvoiceLineType,

    BEGIN OF ResponseType,
      ReferenceID  TYPE IdentifierType,
      ResponseCode TYPE CodeType,
      Description  TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
    END OF ResponseType,

    BEGIN OF LineResponseType,
      LineReference TYPE LineReferenceType,
      Response      TYPE STANDARD TABLE OF ResponseType WITH EMPTY KEY,
    END OF LineResponseType,

    BEGIN OF DocumentResponseType,
      Response          TYPE ResponseType,
      DocumentReference TYPE DocumentReferenceType,
      LineResponse      TYPE STANDARD TABLE OF LineResponseType WITH EMPTY KEY,
    END OF DocumentResponseType,

    BEGIN OF DespatchLineType,
      Id                  TYPE IdentifierType,
      Note                TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      DeliveredQuantity   TYPE QuantityType,
      OutstandingQuantity TYPE QuantityType,
      OutstandingReason   TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      OversupplyQuantity  TYPE QuantityType,
      OrderLineReference  TYPE OrderLineReferenceType,
      DocumentReference   TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      Item                TYPE ItemType,
      Shipment            TYPE STANDARD TABLE OF ShipmentType WITH EMPTY KEY,
    END OF DespatchLineType,

    BEGIN OF ReceiptLineType,
      Id                    TYPE IdentifierType,
      Note                  TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      ReceivedQuantity      TYPE QuantityType,
      ShortQuantity         TYPE QuantityType,
      RejectedQuantity      TYPE QuantityType,
      RejectReasonCode      TYPE CodeType,
      RejectReason          TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      OversupplyQuantity    TYPE QuantityType,
      ReceivedDate          TYPE DateType,
      TimingComplaintCode   TYPE CodeType,
      TimingComplaint       TYPE TextType,
      OrderLineReference    TYPE OrderLineReferenceType,
      DespatchLineReference TYPE LineReferenceType,
      DocumentReference     TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      Item                  TYPE ItemType,
      Shipment              TYPE STANDARD TABLE OF ShipmentType WITH EMPTY KEY,
    END OF ReceiptLineType.

ENDINTERFACE.