INTERFACE zif_etr_invoice_ubl21
  PUBLIC .

  INTERFACES:
    zif_etr_common_ubl21.

  ALIASES:
    IdentifierType        FOR zif_etr_common_ubl21~IdentifierType,
    IndicatorType         FOR zif_etr_common_ubl21~IndicatorType,
    DateType              FOR zif_etr_common_ubl21~DateType,
    TimeType              FOR zif_etr_common_ubl21~TimeType,
    CodeType              FOR zif_etr_common_ubl21~CodeType,
    TextType              FOR zif_etr_common_ubl21~TextType,
    NumericType           FOR zif_etr_common_ubl21~NumericType,
    PeriodType            FOR zif_etr_common_ubl21~PeriodType,
    OrderReferenceType    FOR zif_etr_common_ubl21~OrderReferenceType,
    DocumentReferenceType FOR zif_etr_common_ubl21~DocumentReferenceType,
    BillingReferenceType  FOR zif_etr_common_ubl21~BillingReferenceType,
    SignatureType         FOR zif_etr_common_ubl21~SignatureType,
    CustomerPartyType     FOR zif_etr_common_ubl21~CustomerPartyType,
    SupplierPartyType     FOR zif_etr_common_ubl21~SupplierPartyType,
    PartyType             FOR zif_etr_common_ubl21~PartyType,
    PaymentMeansType      FOR zif_etr_common_ubl21~PaymentMeansType,
    PaymentTermsType      FOR zif_etr_common_ubl21~PaymentTermsType,
    AllowanceChargeType   FOR zif_etr_common_ubl21~AllowanceChargeType,
    ExchangeRateType      FOR zif_etr_common_ubl21~ExchangeRateType,
    TaxTotalType          FOR zif_etr_common_ubl21~TaxTotalType,
    MonetaryTotalType     FOR zif_etr_common_ubl21~MonetaryTotalType,
    DeliveryType          FOR zif_etr_common_ubl21~DeliveryType,
    InvoiceLineType       FOR zif_etr_common_ubl21~InvoiceLineType,
    UBLExtensionsType     FOR zif_etr_common_ubl21~UBLExtensionsType.

  TYPES:
    BEGIN OF InvoiceType,
      UBLExtensions                  TYPE UBLExtensionsType,
      UBLVersionID                   TYPE IdentifierType,
      CustomizationID                TYPE IdentifierType,
      ProfileID                      TYPE IdentifierType,
      Id                             TYPE IdentifierType,
      CopyIndicator                  TYPE IndicatorType,
      UUId                           TYPE IdentifierType,
      IssueDate                      TYPE DateType,
      IssueTime                      TYPE TimeType,
      InvoiceTypeCode                TYPE CodeType,
      Note                           TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      DocumentCurrencyCode           TYPE CodeType,
      TaxCurrencyCode                TYPE CodeType,
      PricingCurrencyCode            TYPE CodeType,
      PaymentCurrencyCode            TYPE CodeType,
      PaymentAlternativeCurrencyCode TYPE CodeType,
      AccountingCost                 TYPE TextType,
      LineCountNumeric               TYPE NumericType,
      InvoicePeriod                  TYPE PeriodType,
      OrderReference                 TYPE OrderReferenceType,
      BillingReference               TYPE STANDARD TABLE OF BillingReferenceType WITH EMPTY KEY,
      DespatchDocumentReference      TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      ReceiptDocumentReference       TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      OriginatorDocumentReference    TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      ContractDocumentReference      TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      AdditionalDocumentReference    TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      Signature                      TYPE STANDARD TABLE OF SignatureType WITH EMPTY KEY,
      AccountingSupplierParty        TYPE SupplierPartyType,
      AccountingCustomerParty        TYPE CustomerPartyType,
      BuyerCustomerParty             TYPE CustomerPartyType,
      SellerSupplierParty            TYPE SupplierPartyType,
      TaxRepresentativeParty         TYPE PartyType,
      Delivery                       TYPE STANDARD TABLE OF DeliveryType WITH EMPTY KEY,
      PaymentMeans                   TYPE STANDARD TABLE OF PaymentMeansType WITH EMPTY KEY,
      PaymentTerms                   TYPE PaymentTermsType,
      AllowanceCharge                TYPE STANDARD TABLE OF AllowanceChargeType WITH EMPTY KEY,
      TaxExchangeRate                TYPE ExchangeRateType,
      PricingExchangeRate            TYPE ExchangeRateType,
      PaymentExchangeRate            TYPE ExchangeRateType,
      PaymentAlternativeExchangeRate TYPE ExchangeRateType,
      TaxTotal                       TYPE STANDARD TABLE OF TaxTotalType WITH EMPTY KEY,
      WithholdingTaxTotal            TYPE STANDARD TABLE OF TaxTotalType WITH EMPTY KEY,
      LegalMonetaryTotal             TYPE MonetaryTotalType,
      InvoiceLine                    TYPE STANDARD TABLE OF InvoiceLineType WITH EMPTY KEY,
    END OF InvoiceType.
ENDINTERFACE.